# Generated by Django 4.2.3 on 2023-07-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentjustificationanswer',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentquizanswer',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
