# Generated by Django 4.2.3 on 2023-07-16 11:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_studentjustificationanswer_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenquiz',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
