# Generated by Django 4.2.3 on 2023-07-18 13:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_takenquiz_percentage_takenquiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='avg_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
