# Generated by Django 4.2.3 on 2023-07-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_teachermodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
