# Generated by Django 4.2.3 on 2023-07-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_studentmodel_name_teachermodel_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
