# Generated by Django 4.2.4 on 2023-08-05 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_teachermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.teachermodel'),
        ),
    ]
