# Generated by Django 4.2.4 on 2023-08-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_hashkeys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashkeys',
            name='user',
        ),
        migrations.AddField(
            model_name='hashkeys',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1:8000', unique=True),
            preserve_default=False,
        ),
    ]
